### ISSUE TITLE
Admin POST new account burns REDIS auto index

### ISSUE THREAD

**Issue by Neil-Jubinville** [emschwartz/interledger-rs#126]
Hi,  I am building up my knowledge of the rust implementation and the ILP spec at the same time.  

In my learning I have abstracted an ILP node to run outside the docker and then I began to POST accounts to that local running connector.

Here is what happened:

- The first one went in fine.   I was able to see it in REDIS.
- The second one however failed with a HTTP 500 error. 
- I had changed only the ILP address in my post request. 
- Then I thought I should change the admin token in the POST so the new user/account would have a unique token.
-  BAM! it goes into REDIS.  Success.

After viewing the REDIS store I could see the account index jumped from 0 to next account_id = 5
Since I only had two successful entries, they list as below.   The failed attempts increased the index id.   

accounts:0
accounts:4

I am logging this because I would expect the index to be sequential on success and that a failure to process should maybe not burn the indexing.

Neil

**Comment by gakonst** [comment]
Good find, this happens due to [`next_account_id`](https://github.com/emschwartz/interledger-rs/blob/master/crates/interledger-store-redis/src/store.rs#L252-L258) incrementing the number even though the rest of the call can fail. 

We can probably just add a DECR in a `map_err` to fix this. Also, it might not be a good idea to only allow unique tokens? @emschwartz

**Comment by emschwartz** [comment]
Thanks Neil for spotting this and opening the issue!

I agree with @gakonst's solution.

> it might not be a good idea to only allow unique tokens?

Probably. Right now there's no "username" part of the login so the tokens need to be unique. I would be open to switching it to login with the account ID (or a separate username) and the API key so that they keys don't need to be globally unique.

**Comment by emschwartz** [comment]
After thinking about this some more, I realized that simply decrementing the ID in case creating the account fails isn't safe because it would set it to the wrong number if another account happened to be created in that time. (Meaning you could end up in a case where account 1 failed to be created, account 2 exists, but the `next_account_id` is now set to 2 instead of 1)

We should definitely add usernames (tracked in https://github.com/emschwartz/interledger-rs/issues/147) and make it so the token does not have to be globally unique.

There is an open question then about whether we should have account IDs separate from the usernames at all (numeric or not). As @Neil-Jubinville pointed out elsewhere, interacting with the API using numeric IDs is not very developer friendly (`/accounts/bob` is nicer than `/accounts/4`), so we might not actually need the numeric IDs. The username could be substituted for the ID throughout the codebase (and I think the only change would actually happen in the Redis store).

**Comment by emschwartz** [comment]
Folding this issue into https://github.com/emschwartz/interledger-rs/issues/186
