### ISSUE TITLE
Store Idempotency Key: Optional or Mandatory?

### ISSUE THREAD

**Issue by gakonst** [emschwartz/interledger-rs#131]
We might want to propose making the idempotency_key required in the API standard. Currently the implementations of the engine and settlement APIs use an optional key.

https://stripe.com/docs/api/idempotent_requests
> To perform an idempotent request, provide an additional Idempotency-Key: <key> header to the request.

"an additional..." would make me think that it should be optional

**Comment by adrianhopebailie** [comment]
I believe the intention was always for it to be optional. Are suggesting it should change to be mandatory or just saying the language is unclear.

**Comment by gakonst** [comment]
Optional is my current understanding as well, just echoing a short discussion we had with @emschwartz around it

**Comment by emschwartz** [comment]
Do we have a good reason for making it optional? I don't think there's actually a safe way to use this API if you don't make idempotent requests. If that's the case, requiring that field would mean a) you have to try harder to shoot yourself in the foot and b) there are fewer code paths for us to check and thus fewer places for bugs to find.

In either case, @gakonst even if the field is optional on the HTTP API, I don't think it should be optional in the store's API (because calling a function like `load_idempotent_data` with `None` doesn't make any sense). Instead, the HTTP API should handle the `None` case and only call the store if an `idempotency_key` was passed in.

**Comment by emschwartz** [comment]
I think we're leaving it as optional so I'll close this for now
