### ISSUE TITLE
Balance Service split to Incoming / Outgoing

### ISSUE THREAD

**Issue by gakonst** [emschwartz/interledger-rs#168]
`update_balances_for_prepare` does not meaningfully use the receiving account or the outgoing amount. 

`update_balances_for_fulfill` does not meaningfully use the sending account or the incoming amount. 

We can probably split the Balance Service in an outgoing service for the fulfill's and an incoming service for the prepares, and adjust the trait

**Comment by emschwartz** [comment]
https://github.com/emschwartz/interledger-rs/pull/164 changes those two functions to not take the unused parameters.

Given this change, the only real benefit I see of splitting the balance service would be removing the [`original_amount`](https://github.com/emschwartz/interledger-rs/blob/4cafdba4b4ce62cf61ad73815fcb5511d1c784d1/crates/interledger-service/src/lib.rs#L65) field from the `OutgoingRequest`. One potential downside is that splitting them could invite issues where only one is used and not the other, though maybe we don't need to worry too much about that because that would be a compile-time issue.
