### ISSUE TITLE
Settlement Engine Asset Scale

### ISSUE THREAD

**Issue by gakonst** [emschwartz/interledger-rs#185]
1. Should the asset scale conversion be done on the connector or on the engine?
If we do it on the engine, it'd mean that each engine would have to implement that conversion properly, while we could do it on the operator once.

2. How do we handle settlement amounts that are bigger than u64 in the store? Can occur in high granularity EVM transactions (Ether / ERC20 / any other Ethereum fork)

cc @emschwartz @kincaidoneil @sappenin

**Comment by emschwartz** [comment]
A couple of thoughts:
- The connector must be able to use atomic mathematical operations in the database
- All databases support u64 but I'm not sure most or any support larger formats
- Higher precision numbers are mostly an issue because the EVM chose a stupidly large number format, so ideally the implications of that decision would be limited to components that directly touch Ethereum-related things
- If the SE receives a settlement for an amount greater than what the connector supports, the SE might not have a way to "return" that settlement. Therefore, it's important that the connector be able to process whatever the SE sends it -- unless it would end up being up to the SE to submit many "incoming settlements" to represent the one larger amount it got

In practice, most applications using ETH seem to use Gwei instead of Wei, which makes the numbers more reasonable. Is this also true for ERC20 tokens? Or would you ever send 10^-18 Dai?

**Comment by gakonst** [comment]
> In practice, most applications using ETH seem to use Gwei instead of Wei, which makes the numbers more reasonable. Is this also true for ERC20 tokens? Or would you ever send 10^-18 Dai?

If you want to support the micropayments use case, and if the asset you're using is very valuable, then it could be expected that you'd want sub 1e-9 payments

**Comment by emschwartz** [comment]
Actually the question isn't really whether you want to support micropayments, it's whether you want to support micropayments _and_ larger payments. If you are using ETH (or an ERC20) to send micropayments, you could configure your scale to be 12 or 18 or something like that, but that would just limit how large a payment you can send.

**Comment by kincaidoneil** [comment]
I propose we use the design in the RFC:

- **No additional configuration on the connector**. This is a potential footgun.
- **Stateless**. Less configuration to be persisted and looked up from the DB every request.
- **Different scales for different accounts**. If some accounts are denominated in different assets, but use the same SE, those accounts can cleanly use different different scales. This may be important to support multi-asset SE instances, which the current API doesn't preclude.

> If the SE receives a settlement for an amount greater than what the connector supports, the SE might not have a way to "return" that settlement. Therefore, it's important that the connector be able to process whatever the SE sends it -- unless it would end up being up to the SE to submit many "incoming settlements" to represent the one larger amount it got

Yes and no. Per the proposal in the RFC, the connector needs to _process_ whatever amount the SE sends it--likely requiring big number logic--but not _persist_ whatever amount the SE sends it, since it just tells the SE "only credited _x_ amount in my scale." So this doesn't require the DB to support greater than u64 atomic operations; only u64 values should touch the accounting system's DB. The SE is then responsible for persisting and adding the leftover amount to subsequent incoming settlements, and the idea is that the "dust" amount will eventually accumulate to greater than 1 unit in the connector's scale so it gets credited.

> How do we handle settlement amounts that are bigger than u64 in the store? Can occur in high granularity EVM transactions (Ether / ERC20 / any other Ethereum fork)

If the amount in settlements is greater than u64, the settlement engine may need to persist those values to the DB, yes. 

I understand why for the balance logic in the connector we need the DB to support a command like this: "For key-abc, if the value > x, add y to the value"

And, SEs will require some DB-related atomic operations (e.g. atomically get then delete this value), and job queues or mutexes for async operations, but why does the SE require atomic "add if less than" operations performed within the DB? Can't we store all the SE's big numbers as strings or another data type?

(Also, I think we can atomically add to a big number field like this):
1. Atomically get and delete the value from the DB as a string
2. Within the SE, add the existing value with the addend using a bignumber library
3. Atomically set the new value in the DB only if it's unset -- otherwise, start over from step 1

> it'd mean that each engine would have to implement that conversion properly, while we could do it on the operator once.

Yes and no.

The _conversion logic_ is duplicated. But this is trivial with most big number libraries. To handle incoming settlement notifications on the connector: `new BN(amountFromSE).exponentiatedBy(connectorScale - scaleFromSE).roundDown()` is the amount that should be credited to the account and included in the response ACK back to the SE. On the SE's end, the only difference is subtracting the connector's scale from its scale, then subtracting that amount from the original amount to settle to determine the amount leftover.

The logic to persist the leftover amount is not duplicated, since it's required anyways. If the incoming settlement requests to the connector fail, SEs should persist that amount to try again later (and add to subsequent incoming settlements) anyways. So persisting a "leftover" amount and adding that to subsequent settlements is very similar functionality.

Also, this could be abstracted out into a framework used for many SEs, in the same way you abstracted out the idempotency and retry logic (which IMO is much harder to implement well!).

**Comment by matdehaast** [comment]
cc @adrianhopebailie

**Comment by adrianhopebailie** [comment]
I propose we pass the asset scale in the API calls (as @kincaidoneil proposes in the RFC) but encourage implementations to only do safe conversions and reject requests if there is any chance of lost precision.

In fact, we should allow implementations to reject requests even if the scale is simply different to their own (i.e. they refuse to do a conversion)

In most deployments all components will be configured to use the same scale so this won't be a problem.

Why bother then?

If we don't pass the scale in the message then we assume that operators will configure the scale on all components AND won't get it wrong. That's a possible disaster as errors are literally in orders of magnitude.

**Comment by gakonst** [comment]
> In fact, we should allow implementations to reject requests even if the scale is simply different to their own (i.e. they refuse to do a conversion)

I prefer this solution; reject if precision would be lost, instead of rounding down and keeping track of leftovers.

**Comment by emschwartz** [comment]
> In most deployments all components will be configured to use the same scale so this won't be a problem.

Is that true? Aren't we using a scale of 9 for XRP (where it can only settle with a scale of 6) and ETH (that would have a scale of 18)?

> In fact, we should allow implementations to reject requests even if the scale is simply different to their own (i.e. they refuse to do a conversion)

If this happens, what should the caller do? This seems like a serious issue because it would mean incoming money hasn't been accounted for. I would want to have some way to ensure that my setup is correct initially and be sure that this won't happen at runtime.

**Comment by adrianhopebailie** [comment]
> Is that true?

Yes, per settlement engine. 

> If this happens, what should the caller do? This seems like a serious issue because it would mean incoming money hasn't been accounted for.

It's not that serious. It means the account in the accounting system doesn't get credited until the operator realises their error and fixes the issue. Nobody loses money.

> I would want to have some way to ensure that my setup is correct initially and be sure that this won't happen at runtime.

Not mutually exclusive but that would still require some messages exchanged between the two systems to establish if there is a config mismatch.

**Comment by emschwartz** [comment]
> Yes, per settlement engine.

Sorry, maybe I'm not understanding what you mean but how is that the case if you clear ILP packets denominated in 10^-9 XRP but can only settle in drops (10^-6)?

> It means the account in the accounting system doesn't get credited until the operator realises their error and fixes the issue. Nobody loses money.

Agreed, though I'm not quite sure how the operator would discover this initially. If none of your settlements are coming through, the service would stop because you'd think the other person wasn't settling. Not great but you'd probably find that out relatively fast. If some of the settlements weren't credited, you would just think the peer was underpaying you. It's definitely not catastrophic but it sounds pretty annoying.

> Not mutually exclusive but that would still require some messages exchanged between the two systems to establish if there is a config mismatch.

I'd be supportive of adding that type of exchange if it helped catch this type of bug right away

**Comment by adrianhopebailie** [comment]
> Sorry, maybe I'm not understanding what you mean but how is that the case if you clear ILP packets denominated in 10^-9 XRP but can only settle in drops (10^-6)?

Why would you configure your connector and SE to use different scales for the same currency?

> though I'm not quite sure how the operator would discover this initially

Surely this would be logged as a critical error immediately, the same as low liquidity or failed settlements etc

**Comment by adrianhopebailie** [comment]
> I'd be supportive of adding that type of exchange if it helped catch this type of bug right away

Sure, but would that mean we don't need it in the other messages anymore?

**Comment by kincaidoneil** [comment]
> Why would you configure your connector and SE to use different scales for the same currency?

Right now, we have plugin integrations with merely 3 different assets (excluding ERC-20 tokens). Despite this very small sample size, we _already_ have examples of:

- **Scale at the clearing layer with greater precision than the settlement layer**: Strata and Coil needed XRP to be 10^-9 in order to prevent rounding errors with their very small micropayments, _even though_ XRP settlements can only be denominated as precise as drops.
- **Scale at the settlement layer with greater precision than the clearing layer**: ETH settlements and payment channel claims must be denominated in its smallest unit, wei (10^-18 ETH). However, if we used units of wei at the clearing layer, any value that’s limited to u64 (e.g. ILP packet amounts, or balances) is capped to ~18 ETH. Using wei also caused issues with STREAM probing the exchange rate. So, units of gwei, or 10^-9 ETH, are typically used at the clearing layer.
- **Changing the clearing layer's scale**: `ilp-plugin-xrp-asym-server` and `-client` originally used an asset scale of 6. Later, Coil/Strata changed the plugins to use an asset scale of 9. This had the unfortunate result of breaking moneyd for all other live connectors that were using the old version with an asset scale of 6. The lesson to be learned is not that this was a bad decision, but rather that their use case demanded that _they increase the precision after the fact_. To support this, we need to ensure it's a bilateral accounting concern at the clearing layer between peers as to not break users who don't desire that additional precision.

These empirical examples imply to me there may be more use cases in the future we're not foreseeing and need to support varying precision between the two layers.

**Comment by gakonst** [comment]
> Scale at the clearing layer with greater precision than the settlement layer: Strata and Coil needed XRP to be 10^-9 in order to prevent rounding errors with their very small micropayments, even though XRP settlements can only be denominated as precise as drops.

Note that Ethereum assets having 18 decimals allows handling micropayments (doubtful you'll need less than 1 Wei) without having this difference in the asset scale, since you'd set both engine and connector at 18.

**Comment by emschwartz** [comment]
@gakonst can this issue be closed?
