### ISSUE TITLE
Limit number of TODOs on CI

### ISSUE THREAD

**Issue by gakonst** [emschwartz/interledger-rs#97]
Let's add a restriction on the CI to keep our TODOs below a certain amount? Currently there are 93 todos, maybe 75 would be a good first target, if there are low hanging fruit.

maybe worth integrating https://github.com/naholyr/github-todos to track these? maybe https://github.com/JasonEtco/todo

**Comment by emschwartz** [comment]
I'm not a huge fan of that idea, just because it may incentivize leaving out important TODOs while writing code rather than fixing old ones. Once we have some of the highest priority features (like settlement) working, we can prioritize going through the whole code base and tackling those smaller issues
